# Generated by Django 4.2.12 on 2024-10-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empanadas', '0002_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='empanada',
            name='image',
            field=models.ImageField(default='imagesEmapanadas/default.png', upload_to='imagesEmapanadas/'),
        ),
    ]
