# Generated by Django 4.2.12 on 2024-10-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empanadas', '0003_empanada_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empanada',
            name='image',
            field=models.ImageField(default='imagesEmpanadas/default.png', upload_to='imagesEmpanadas/'),
        ),
    ]
