# Generated by Django 5.1.2 on 2024-12-12 11:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
        ('empanadas', '0004_alter_empanada_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('idCommande', models.AutoField(primary_key=True, serialize=False)),
                ('dateCommande', models.DateField(default=datetime.date.today)),
                ('payee', models.BooleanField(default=False)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.tiendauser')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('idLigneCommande', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('commande_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paniers.commande')),
                ('empanada_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empanadas.empanada')),
            ],
        ),
    ]
