# Generated by Django 5.1.2 on 2024-12-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paniers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='lignecommande',
            old_name='commande_id',
            new_name='commande',
        ),
        migrations.RenameField(
            model_name='lignecommande',
            old_name='empanada_id',
            new_name='empanada',
        ),
    ]
